name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.rst"
      - ".*"

  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.rst"
      - ".*"

  workflow_dispatch:

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      # with '-e py' tox runs the python version of the current environment
      - name: Unittests with tox
        run: tox -e py

      # Coverage does not work for private repos
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
        with:
          files: ./coverage.xml # optional
